---
- hosts: 172.31.8.99
  become: yes
  tasks:
   - name: execute linux commands
     command: hostname -f 
     register: theabovehostnameis

   - name: print my first command result
     debug:
       msg: "{{theabovehostnameis}}"

   - name: install tree software
     dnf:
      name: tree
      state: present
     when: theabovehostnameis.stderr!=""

   - name: install wget software
     dnf:
      name: wget
      state: present
     when: theabovehostnameis.stderr==""
