---
- hosts: 172.31.8.99
  become: yes
  tasks:
   - name: execute linux commands
     command: hostname -f 
     register: theabovehostnameis

   - name: print my first command result
     degub:
       msg: "{{theabovehostnameis}}"