---
- hosts: productionservers
  become: yes
  vars_files:
    - vars.yml
  tasks:
    - name: Install httpd
      dnf:
        name: "{{ mywebpackonredhat }}"
        state: present

    - name: Start httpd service, if not started
      service:
        name: "{{ mywebpackonredhat }}"
        state: started

    - name: Install git
      dnf:
        name: git
        state: present

    - name: Install tree
      dnf:
        name: tree
        state: present

    - name: Install java
      dnf:
        name: "{{ installjavaonredhat }}"
        state: present
