---
- hosts: all
  become: yes
  tasks:
  - name: install httpd
    dnf:
     name: httpd
     state: present

  - name: install git
    dnf:
     name: git
     state: present


  - name: install tree
    dnf:
     name: tree
     state: present



