---
- hosts: all
  become: yes
  tasks:
  - name: install httpd
    dnf:
     name: httpd
     state: present
     
  - name: Start service httpd, if not started
    service: 
     name: httpd
     state: started

  - name: install git
    dnf:
     name: git
     state: present


  - name: install tree
    dnf:
     name: tree
     state: present



